config/routes.rb
Rails.application.routes.draw do
  
  namespace :api do
    namespace :v1 do

      resources :books      
    end
  end

  resources :authors do
    resources :comments
  end

  resources :books do
    resources :comments
  end

    root 'books#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :comments, :as => :commentable
	has_many :photos, :as => :photoable
	has_and_belongs_to_many :books, :join_table => :author_books

	has_attached_file :photo, styles: { medium: "200x200>", thumb: "50x50>" },
	default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/author_book.rb
class AuthorBook < ActiveRecord::Base
	belongs_to :author
	belongs_to :book

	validates_uniqueness_of :AuthorBook_id, scope: [:author_id, :book_id]
end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :comments, :as => :commentable
	has_many :cover, :as => :photoable
	has_and_belongs_to_many :authors, :join_table => :author_books

	has_attached_file :cover, styles: { medium: "200x200>", thumb: "50x50#" },
	default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/


  	def original_url
  		root_url = "http://localhost:3000"
  		root_url + cover.url
	end
 end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :commentable, polymorphic: true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
	belongs_to :photoable, polymorphic: true
end

app/controllers/api/v1/books_controller.rb
class Api::V1::BooksController < ApplicationController

	respond_to :json
	def index
      @books = Book.all
    end

    def show
      @book = Book.find(params[:id])
    end    	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
    @author = Author.find(params[:id])
    @commentable = @author
    @comments = @commentable.comments
    @comment = Comment.new
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
    @author = Author.find(params[:id])
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.delete
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :photo)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.page(params[:page]).per(5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book=Book.find(params[:id])
    @commentable = @book
    @comments = @commentable.comments
    @comment = Comment.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  def new
    @book = Book.new
    @author_ids = Author.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
      format.js
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
    respond_to do |format|
    format.html
    format.js
    end
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book}
        format.js
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.delete
    
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :cover, :author_ids => [])
    end

    def show_authors
      @author = Author.find(params[:id])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_commentable

  def index
  	@comments = @commentable.comments
  end

  def new
  	@comment = @commentable.comments.new
  end

  def create
  	#@comment = @commentable.comments.new(params[:comment])
  	@comment = Comment.new(comment_params)

  	if @comment.save
  		redirect_to [@commentable, :comments], notice:"Comment created"
  	else
  		render :new
  	end
  end

  private

  	def load_commentable
  		resource, id = request.path.split('/')[1,2]
  		@commentable = resource.singularize.classify.constantize.find(id)
  	end
  	def comment_params
      params.require(:comment).permit(:content)
    end

end

app/helpers/api/v1/books_helper.rb
module Api::V1::BooksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div>
    <%= f.label :Photo %>
    <%= f.file_field :photo %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>
<br>
<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= image_tag author.photo.url(:thumb) %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  &nbsp;&nbsp;<%= @author.name %>
</p>

<p>
  <strong>Cover:</strong>
  &nbsp;&nbsp;<%= image_tag @author.photo.url(:medium) %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

<h2>Comments</h2>
<%= render "comments/comments" %>
<%= render "comments/form" %>

app/views/books/_book.html.erb
<tr id="book_<%= book.id %>">
        <td><%= book.title %></td>
        <td><%= image_tag book.cover.url(:thumb) %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book), :remote => true %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' }, :remote => true %></td>
</tr>

app/views/books/_form.html.erb
<%= form_for @book, :remote => true do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <br>
  <div class="field">
    <%= f.label :Book_Cover %>
    <%= f.file_field :cover %>
  </div>
  <br>
  <p>
    <%= f.label :Author %><br>
    <%= f.collection_select(:author_ids, Author.all, :id ,:name, {}, {:multiple => true}) %>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/create.js.erb
<% if @book.errors.count == 0 %>

	$('#new_book').remove();
	$('#new_book_link').show();
	$('#books').append('<%= j render("book", :book => @book) %>');

<% else %>

	$('.new_book').remove();
	$('#new_book_link').after('<%= j render("form") %>');

<% end %>

app/views/books/destroy.js.erb
$('#book_<%= @book.id %>').remove();

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/edit.js.erb
$('#new_book_link').hide().after('<%= j render("form") %>');

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= paginate @books %>
    <% @books.each do |book| %>
      <%= render "book", :book => book %> 
    <% end %>
    
  </tbody>
</table>
<%= paginate @books %>
<br>

<%= link_to 'New Book', new_book_path, :remote => true, :id => "new_book_link" %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', books_path %>

app/views/books/new.js.erb
$('#new_book_link').hide().after('<%= j render("form") %>');

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  &nbsp;&nbsp;&nbsp;&nbsp;<%= @book.title %>
</p>
<br>
<p>
  <strong>Cover:</strong>
  &nbsp;&nbsp;<%= image_tag @book.cover.url(:medium) %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

<h2>Comments</h2>
<%= render "comments/comments" %>
<%= render "comments/form" %>

app/views/comments/_comments.html.erb
<div id="comments">
<% @comments.each do |comment| %>
	<div class="comment">
		<%= simple_format comment.content %>
	</div>
<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for [@commentable, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div class="error_messages">
      <h2>Please correct the following errors.</h2>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :content, rows: 8 %>
  </div> 
  <div class="actions">
  	<%= f.submit %>
  </div>
<% end %>

app/views/comments/index.html.erb
<h1>Comments</h1>

<%= render 'comments' %>

<p><%= link_to "New Comment", [:new, @commentable, :comment] %></p>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BooksApp</title>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Books app</a>
    </div>
    
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>
<script src="//railsgirls.com/assets/bootstrap.js"></script>

</body>
</html>